[package]
name = "mitre"
version = "0.1.0"
authors = ["Lee Hambley <lee.hambley@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
prettytable-rs = "^0.8"
libc = "0.2.33"
chrono = "0.4.13"

[lib]
name = "libmitre"
path = "src/lib.rs"

[[bin]]
name = "mitre"
path = "src/main.rs"