[package]
name = "mitre"
version = "0.1.0"
authors = ["Lee Hambley <lee.hambley@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.13"
clap = "3.0.0-beta.1"
libc = "0.2.33"
prettytable-rs = "^0.8"
simple_logger = "1.6.0"
envsubst = "0.2.0"
filesystem = "0.4.4"

[lib]
crate-type = ["dylib"]
name = "mitre"
path = "src/lib.rs"

[[bin]]
name = "mitre"
path = "src/main.rs"
